<a href="https://colab.research.google.com/github/VenissaCarolQuadros/COMP551/blob/main/COMP551_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import requests
import pandas as pd
import numpy as np

In [3]:
def read_data(url, dest):
  response = requests.get(url)
  with open(dest, 'wb') as file:
      file.write(response.content)
  return

In [10]:
dest1= 'LinearRegression.xlsx'
read_data("https://raw.githubusercontent.com/VenissaCarolQuadros/COMP551/main/data/ENB2012_data.xlsx", dest1)
df1= pd.read_excel(dest1)

dest2= 'LogisticRegression.csv'
read_data('https://raw.githubusercontent.com/VenissaCarolQuadros/COMP551/main/data/Qualitative_Bankruptcy/Qualitative_Bankruptcy.data.txt', dest2)
df2= pd.read_csv(dest2, header=None)


In [20]:
print(df1.shape, df2.shape) ##Verifying dataset size
print( df1[df1.eq('?').any(1)],  df2[ df2.eq('?').any(1)]) #Checking for nulls
##No nulls found. Dataset size seems right

(768, 10) (250, 7)
Empty DataFrame
Columns: [X1, X2, X3, X4, X5, X6, X7, X8, Y1, Y2]
Index: [] Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6]
Index: []


##Linear Regression

In [22]:
class LinearRegression():
  def __init__(self):
    ()
  def fit(self, X, Y):
    return
  def predict(self):
    return

SyntaxError: ignored

In [28]:
#Train test split
train=df1.sample(frac=0.8,random_state=200)
test=df1.drop(train.index)

X_train= np.c_[np.ones(train.shape[0]), train.iloc[:, :8].to_numpy(copy=True)] ##Adding column of 1s for bias
Y_train= train.iloc[:, 8:].to_numpy(copy=True)

print(X_train.shape, Y_train.shape)


(614, 9) (614, 2)


In [32]:
w= np.linalg.inv(X_train.T @ X_train)@X_train.T@Y_train

In [44]:
X_test= np.c_[np.ones(test.shape[0]), test.iloc[:, :8].to_numpy(copy=True)]
Y_test= test.iloc[:, 8:].to_numpy(copy=True)

Y_predict= X_test@ w


loss=np.sum((Y_test-Y_predict)**2, axis=0)
print(np.c_[Y_test, Y_predict])

[[ 15.55        21.33       122.22189805 135.93725897]
 [ 15.55        21.33       122.17824828 136.19057103]
 [ 20.71        25.16        75.09851687  84.05084205]
 [ 19.68        29.6         75.07669198  84.17749809]
 [ 19.34        23.49        50.33812022  57.49257313]
 [ 29.9         31.27        25.38677837  29.06989616]
 [  6.4         11.72        21.4509815   28.15594947]
 [ 10.77        16.75        58.49447736  68.15194188]
 [ 10.56        16.67        58.47265247  68.27859791]
 [ 24.59        26.29       124.38467018 137.83901599]
 [ 29.03        32.92        77.37041343  85.31931892]
 [ 35.94        43.33        27.57137538  30.84499715]
 [ 32.94        34.14        27.38043018  28.9805891 ]
 [ 10.71        13.8         23.70105318  29.55108236]
 [ 10.8         14.28        23.67922829  29.6777384 ]
 [ 10.75        14.27        23.63557851  29.93105046]
 [ 11.13        14.61        43.131961    50.80688555]
 [ 11.68        13.9         41.31364121  48.29127159]
 [ 11.69  